[global]
dsn = "root:@tcp(172.17.0.1:3306)/"
database = "test"
target = "tidb"
thread = 4
action = 10
log-path = "./logs"
anomaly = false

[graph]
begin = 2
commit = 2
rollback = 2
select = 3
select-for-update = 3
insert = 5
update = 5
delete = 5

[depend]
ww = 1
wr = 1
rw = 1
